export const SECRET_ARN = process.env.SECRET_ARN || '';
export const SECRET_CONTENTFUL_WEBHOOK_AUTH_PASSWORD_KEY = (
  process.env.SECRET_CONTENTFUL_WEBHOOK_AUTH_PASSWORD_KEY || ''
);
export const SECRET_CONTENTFUL_WEBHOOK_AUTH_USERNAME_KEY = (
  process.env.SECRET_CONTENTFUL_WEBHOOK_AUTH_USERNAME_KEY || ''
);

export const SQS_QUEUE_URL = process.env.SQS_QUEUE_URL || '';
