name: CD

on: workflow_dispatch

jobs:

  update-github-cd:
    name: Update GitHub CD

    defaults:
      run:
        working-directory: update-github

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run build
      - name: Create function deployment package
        run: zip -j update-github-function.zip dist/index.js
      - name: Upload function deployment package to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DEPLOYMENT_S3_BUCKET_NAME: ${{ secrets.DEPLOYMENT_S3_BUCKET_NAME }}
        run: aws s3 cp update-github-function.zip s3://$DEPLOYMENT_S3_BUCKET_NAME
