name: Contentful Webhook CI

on:
  push:
    branches:
      - main
    paths:
      - contentful-webhook/**
  pull_request:
    branches:
      - main
    paths:
      - contentful-webhook/**
  workflow_dispatch:

jobs:
  ci:
    name: CI
    defaults:
      run:
        working-directory: contentful-webhook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run build
