name: Infrastructure CI

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
  pull_request:
    branches:
      - main
    paths:
      - infrastructure/**
  workflow_dispatch:

jobs:
  ci:
    name: CI
    defaults:
      run:
        working-directory: infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_INFRASTRUCTURE }}
        with:
          projectBaseDir: infrastructure
