name: Shared CI

on:
  push:
    branches:
      - main
    paths:
      - shared/**
  pull_request:
    branches:
      - main
    paths:
      - shared/**
  workflow_dispatch:

jobs:
  ci:
    name: CI
    defaults:
      run:
        working-directory: shared
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run coverage
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SHARED }}
        with:
          projectBaseDir: shared
      - run: npm run build
