name: Web App CI

on:
  push:
    branches:
      - main
    paths:
      - web-app/**
  pull_request:
    branches:
      - main
    paths:
      - web-app/**
  workflow_dispatch:

jobs:
  ci:
    name: CI
    defaults:
      run:
        working-directory: web-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run build
        env:
          LAMBDA_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          LAMBDA_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LAMBDA_REGION: ${{ secrets.AWS_REGION }}
          LAMBDA_USE_POLICY: false
          LAMBDA_USE_TMPDIR: false
          LAMBDA_DISTRIBUTION_ID: distributionId
          LAMBDA_INVALIDATION_PATH: /*
          LAMBDA_WEB_APP_BUCKET_NAME: webAppBucketName
          CMS_DOLPH_PAGE_COMPONENT_TYPE: ${{ secrets.WEB_APP_CMS_DOLPH_PAGE_COMPONENT_TYPE }}
          CMS_EDUCATION_PAGE_COMPONENT_TYPE: ${{ secrets.WEB_APP_CMS_EDUCATION_PAGE_COMPONENT_TYPE }}
          CMS_HOME_PAGE_COMPONENT_TYPE: ${{ secrets.WEB_APP_CMS_HOME_PAGE_COMPONENT_TYPE }}
          DATA_BUCKET_NAME: ${{ secrets.DATA_BUCKET_NAME }}
          DATA_GITHUB_FILE_KEY: ${{ secrets.DATA_GITHUB_FILE_KEY }}
          SECRET_ARN: ${{ secrets.SECRET_ARN }}
          SECRET_WEB_APP_CMS_CLIENT_ACCESS_TOKEN_KEY: WEB_APP_CMS_CLIENT_ACCESS_TOKEN
          SECRET_WEB_APP_CMS_CLIENT_SPACE_KEY: WEB_APP_CMS_CLIENT_SPACE
          BABEL_DISABLE_CACHE: 1
