name: Web App CI

on:
  push:
    branches:
      - main
    paths:
      - web-app/**
  pull_request:
    branches:
      - main
    paths:
      - web-app/**

jobs:
  ci:
    name: CI

    defaults:
      run:
        working-directory: web-app

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run build
